In [ ]:
Introduction 
NumPy est une librairie utilisée dans presque tous les projets de calcul numérique sous Python.

NumPy fournit des structures de données performantes pour la manipulation de vecteurs, de matrices, de tenseurs. 
On parlera de tableau ou array en Anglais (en fait techniquement, ndarray, pour n-dimension array).

NumPy est écrit en C et en Fortran d'où ses performances élevées lorsque les calculs sont vectorisés 
(formulés comme des opérations sur des tableaux)

Pour utiliser NumPy il faut commencer par l'importer :

#Installation
!pip install numpy

In [2]:
#import
import numpy as np

In [3]:
print(np.__version__)

1.26.4


In [4]:
my_liste = [1, 2, 3]
my_liste

[1, 2, 3]

In [5]:
tab = np.array(my_liste)
tab

array([1, 2, 3])

In [8]:
type(tab)

numpy.ndarray

In [9]:
liste1 = [1, 2, "Amine"]
tab1 = np.array(liste1)
tab1

array(['1', '2', 'Amine'], dtype='<U11')

In [10]:
liste2 = [1, 2, 3.6, 5.89, 10]
tab2 = np.array(liste2)
tab2

array([ 1.  ,  2.  ,  3.6 ,  5.89, 10.  ])

In [3]:
# Création à partir d'un liste
liste = [1, 2, 3, 4, 5]  # Définition de la liste d'élément
array_with_liste = np.array(liste)
print(array_with_liste)  # affiche le numpy array

[1 2 3 4 5]


In [4]:
# Création d'un numpy array à partir d'une liste de listes (matrice)
matrice = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_with_matrice = np.array(matrice)
print(array_with_matrice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
## Création à partir d'un tuple
tuplet = (81,57,66)
np.array(tuplet)

array([81, 57, 66])

In [13]:
## Création à partir d'un dict 1 d
dict = np.array([{"name" : "Faouzi", "last" : "Toujani"}])
print(dict)
print(dict.dtype)

[{'name': 'Faouzi', 'last': 'Toujani'}]
object


In [14]:
## Création à partir d'un dict 2 d
dict2 = np.array([{"name" : {"Faouzi", "Fouade", "Huimel"}} , {"last": {"Toujani", "Matmati", "Nevzi"}} ])
print(dict2)
print(dict2.dtype)

[{'name': {'Fouade', 'Faouzi', 'Huimel'}}
 {'last': {'Matmati', 'Nevzi', 'Toujani'}}]
object


In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
np.arange(5, 20, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [21]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
a.shape

(12,)

In [26]:
b = a.reshape((3, 4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
c = a.reshape((4, 3))
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
d = a.reshape((2, 5))
d

ValueError: cannot reshape array of size 12 into shape (2,5)

In [29]:
tab = np.arange(15)
tab

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
tab.resize((3, 5))
tab

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
tab2 = np.arange(12)
tab2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
tab2.resize((2, 5))
tab2

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [34]:
tab2.resize((2, 5), refcheck=False)
tab2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
tab3 = np.arange(9)
tab3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
tab3.resize((5, 6), refcheck=False)
tab3

array([[0, 1, 2, 3, 4, 5],
       [6, 7, 8, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [39]:
tab4 = np.arange(9)
tab4

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
m = np.resize(tab4, (5, 6))
m

array([[0, 1, 2, 3, 4, 5],
       [6, 7, 8, 0, 1, 2],
       [3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5],
       [6, 7, 8, 0, 1, 2]])

In [5]:
#Créer un numpy array à partir de la fonction zeros
array_zeros = np.zeros((3,3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#Créer un numpy array à partir de la fonction ones
array_ones = np.ones((4,2))
print(array_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
#Créer un numpay array avec la fonction eye 
array_eye = np.eye(5)#Pour créer la matrice identité
array_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.full((2, 5), 8, int)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [42]:
np.full((6, 8), 13, float)

array([[13., 13., 13., 13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13., 13., 13., 13.]])

In [48]:
matrice_diag = np.arange(1,17).reshape(4, 4)
matrice_diag

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [49]:
np.diag(matrice_diag)

array([ 1,  6, 11, 16])

In [53]:
np.diag(matrice_diag, k = -1)

array([ 5, 10, 15])

In [54]:
np.diag(matrice_diag, k = 0)

array([ 1,  6, 11, 16])

In [56]:
a = np.array([5, 6, 7, 8, 9])
a

array([5, 6, 7, 8, 9])

In [58]:
matrice_diagonale = np.diag(a)
matrice_diagonale

array([[5, 0, 0, 0, 0],
       [0, 6, 0, 0, 0],
       [0, 0, 7, 0, 0],
       [0, 0, 0, 8, 0],
       [0, 0, 0, 0, 9]])

In [59]:
matrice_diagonale = np.diag(a, k = 2)
matrice_diagonale

array([[0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [11]:
#Créer un numpay array avec la fonction arange: pour créer des nombre entre le minimum et le maximum avec un pas
array_arange = np.arange(0, 11, 2)
array_arange

array([ 0,  2,  4,  6,  8, 10])

In [14]:
#Créer un numpay array avec la fonction linspace #générer une séquence de nombre 
#entre deux valeurs données avec un nombre de points donné
array_linspace = np.linspace(0, 1, 4)#Très utile pour les graphiques
array_linspace

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [66]:
np.linspace(0, 15, 16).reshape(4, 4)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [62]:
array_linspace2 = np.linspace(0, 5, 6)#Très utile pour les graphiques
array_linspace2

array([0., 1., 2., 3., 4., 5.])

In [72]:
np.linspace(
    1,
    5,
    num=5,
    endpoint=True,
    retstep=False,
    dtype=int,
    axis=0,
)

array([1, 2, 3, 4, 5])

In [73]:
np.linspace(1,10,60 ,dtype = int)

array([ 1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,
        3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,
        6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,
        8,  8,  9,  9,  9,  9,  9,  9, 10])

In [15]:
# Créer un numpy array de valeurs aléatoires avec la fonction random
array_random = np.random.random((5,4))#Utile pour initialiser les poids dans les réseaux de neurones, générer des données d'apprentissage synthétiques
print(array_random)

[[0.57030423 0.42034327 0.94170653 0.13982439]
 [0.87417303 0.51557954 0.16532265 0.72068919]
 [0.23005095 0.48461608 0.56232559 0.39960492]
 [0.66311459 0.35021311 0.53964299 0.32275235]
 [0.23976916 0.51933513 0.91510291 0.45365027]]


In [67]:
uniform_random = np.random.rand( 4 , 5 )
print (uniform_random)

[[0.84388144 0.04628467 0.18101037 0.63298185 0.59888465]
 [0.62426047 0.90949266 0.8691639  0.74539975 0.17640618]
 [0.61334512 0.05471177 0.66912828 0.4413259  0.7048205 ]
 [0.395787   0.11655591 0.57780467 0.05220471 0.95456451]]


In [68]:
normal_random = np.random.randn( 4 , 5 )
print (uniform_random)

[[0.84388144 0.04628467 0.18101037 0.63298185 0.59888465]
 [0.62426047 0.90949266 0.8691639  0.74539975 0.17640618]
 [0.61334512 0.05471177 0.66912828 0.4413259  0.7048205 ]
 [0.395787   0.11655591 0.57780467 0.05220471 0.95456451]]


In [69]:
integer_random = np.random.randint( 10 , 50 , 5 )
print (integer_random)

[37 14 30 40 14]


In [70]:
integer_random = np.random.randint( 1 , 11 , size=( 4 , 5 ))
print (integer_random)

[[10  4  5  2  5]
 [ 1  2  2 10  3]
 [ 5  3  1  7  9]
 [ 8  7 10  3  9]]


In [71]:
for rows in integer_random:
    for column in rows:
        print (column)

10
4
5
2
5
1
2
2
10
3
5
3
1
7
9
8
7
10
3
9


In [8]:
#array 2 d
arr = np.array([[2.2, 1.7], [5.1, 6.3], [7.2, 1.2]])
arr

array([[2.2, 1.7],
       [5.1, 6.3],
       [7.2, 1.2]])

In [80]:
x = np.random.normal(loc = 10, scale = 2, size = (5, 5))
x

array([[10.5750878 , 10.53063627, 11.10058817,  9.46842434, 12.79546601],
       [11.26239063,  6.82169166,  9.95260995,  8.10228139, 10.34584486],
       [ 8.93074628, 10.16639967,  7.63161062, 11.52522179,  7.72023306],
       [ 9.68206509,  7.5911726 , 11.37668075, 15.13765078, 10.57492742],
       [ 9.93644082,  9.09539289,  9.07454848, 12.42055487,  8.45429643]])

In [81]:
x.mean()

10.010918505192665

In [82]:
y = np.random.normal(10, 2, (5, 5))
y

array([[11.51958482, 11.26850566,  7.63228042, 14.82604948,  8.37465392],
       [ 9.68091942, 12.20953835,  9.96717751, 12.56319238, 10.05160634],
       [ 9.54118906, 10.07694779,  9.72649485, 11.05344025,  8.03024018],
       [12.43716576, 10.99338527,  9.53885208,  7.91908067, 14.01806622],
       [ 7.75115594,  3.14793068, 10.06719683,  9.61418506,  8.96251892]])

In [83]:
y.mean()

10.038854314822615

In [84]:
arr = np.random.randint(0, 200, 25)
arr

array([ 76,  34, 169,  50, 182,  29,  82,  79,  85, 113, 108,  72,   0,
       113, 134, 113, 168,  78, 169, 177, 170, 118,  99,  34,  36])

In [85]:
matrix = arr.reshape(5, 5)
matrix

array([[ 76,  34, 169,  50, 182],
       [ 29,  82,  79,  85, 113],
       [108,  72,   0, 113, 134],
       [113, 168,  78, 169, 177],
       [170, 118,  99,  34,  36]])

In [86]:
#les valeurs max par colonnnes
matrix.max(axis=0) 

array([170, 168, 169, 169, 182])

In [87]:
#les valeurs max par lignes
matrix.max(axis=1)

array([182, 113, 134, 177, 170])

In [88]:
#valeur max pour tout matrix
matrix.max()

182

In [90]:
#les valeurs max par lignes
matrix.argmax(axis=0)

array([4, 3, 0, 3, 0], dtype=int64)

In [89]:
#les valeurs max par lignes
matrix.argmax(axis=1)

array([4, 4, 4, 4, 0], dtype=int64)

In [9]:
print("le dimension de tab = ", arr.ndim)
print("le Forma de tab = ", arr.shape)
print("nembre d'elements' tab = ", arr.size)
print("type d'elements' tab = ", arr.dtype)

le dimension de tab =  2
le Forma de tab =  (3, 2)
nembre d'elements' tab =  6
type d'elements' tab =  float64


In [29]:
#Fonction mathématiques basiques
array1=np.array([1, 2, 3, 4, 5])
array_sum = np.sum(array1)
array_mean = np.mean(array1)
array_std = np.std(array1)
array_min = np.min(array1)
array_max = np.max(array1)
array_sqrt = np.sqrt(array1)
array_abs = np.abs(array1)
array_power = np.power(array1, 2)
array_exp = np.exp(array1)
array_log = np.log(np.abs(array1))
array_sin = np.sin(array1)
array_cos = np.cos(array1)
array_median = np.median(array1)
print(f" somme = {array_sum} \n moyenne = {array_mean} \n l'écart type = {array_std} \n min = {array_min} \n max  = {array_max} \n racine carre {array_sqrt} \n valeur absolue = {array_abs} \n array_power {array_power} \n exponentiel {array_exp} \n log = {array_log} \n sin {array_sin} \n cos {array_cos} \n median {array_median}") 

 somme = 15 
 moyenne = 3.0 
 l'écart type = 1.4142135623730951 
 min = 1 
 max  = 5 
 racine carre [1.         1.41421356 1.73205081 2.         2.23606798] 
 valeur absolue = [1 2 3 4 5] 
 array_power [ 1  4  9 16 25] 
 exponentiel [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ] 
 log = [0.         0.69314718 1.09861229 1.38629436 1.60943791] 
 sin [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427] 
 cos [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219] 
 median 3.0


In [16]:
# Produit matriciel
matrice = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
produit_matriciel = np.dot(array_with_matrice, array_with_matrice)
print(produit_matriciel)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [17]:
# Transposée
transposee = np.transpose(array_with_matrice)
print(transposee)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [20]:
# Inversion (pour les matrices carrées non singulières)
inverse = np.linalg.inv(array_eye)
print(inverse)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [-0. -0. -0.  1. -0.]
 [ 0.  0.  0.  0.  1.]]


In [21]:
#Déterminant
determinant=np.linalg.det(array_eye)
print(determinant)

1.0


In [22]:
# Accès aux éléments
array1 = np.array([1,2,3,4,5]) 
premier_element = array1[0]
print(premier_element)

1


In [23]:
array1[-1]

5

In [24]:
array1[2]

3

In [25]:
# Modification d'un élément
array1[0] = 15
print(array1)

[15  2  3  4  5]


In [27]:
# Sélection des éléments qui respectent une condition
condition = array1 > 5
elements_respectant_condition = array1[array1 > 5]
elements_respectant_condition

array([15])

In [29]:
condition = array1 > 3
print(condition)
indices = np.where(array1 > 3)
print(indices)

[ True False False  True  True]
(array([0, 3, 4], dtype=int64),)


In [30]:
array1 > 5

array([ True, False, False, False, False])

In [36]:
# Utilisation de np.where
indices = np.where(array1 > 2)
print(indices)
elements_respectant_condition_np_where = array1[indices]
print(elements_respectant_condition_np_where)

(array([2, 3, 4], dtype=int64),)
[3 4 5]


In [34]:
elements_respectant_condition_np_where = [np.where(array1 >5)]
elements_respectant_condition_np_where

[(array([0], dtype=int64),)]

In [38]:
# Mise à jour d'un numpy array
array1[condition] = 0
print(array1)

[0 2 3 0 0]


In [39]:
#  Slicing et indexation avancée
array6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Slicing
premiere_ligne = array6[0, :]
premiere_ligne

array([1, 2, 3])

In [45]:
#  Slicing et indexation avancée
array6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Slicing
premiere_ligne = array6[ : , 0]
premiere_ligne

array([1, 4, 7])

In [53]:
#sous matrice
array6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sous_matrice = array6[1:3, 1:3]
sous_matrice

array([[5, 6],
       [8, 9]])

In [64]:
array6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
# Indexation avancée
lignes = [1, 2]
colonnes = [0, 1]
elements_selectionnes = array6[lignes, colonnes]
elements_selectionnes

array([4, 8])

In [52]:
# Opérations élémentaires et diffusion (broadcasting)
array7 = np.array([1, 2, 3])
array8 = np.array([4, 5, 6])


# Addition élémentaire
array_addition = array7 + array8
array_addition

array([5, 7, 9])

In [54]:
# Multiplication élémentaire
array_multiplication = array7 * array8
array_multiplication

array([ 4, 10, 18])

In [55]:
# Diffusion (broadcasting)
array9 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array10 = np.array([1, 2, 3])
array9+array10

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [56]:
#r redimensionné le numpy array
array3 = np.arange(9)
array3_redimensionne = array3.reshape((3, 3))
print(array3_redimensionne)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [58]:
array3 = np.arange(9)
array3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
#Ajouter des éléments dans un numpy array
array1_allonge = np.append(array1, [6, 7, 8])
print(array1_allonge)

[0 2 3 0 0 6 7 8]


In [60]:
#Connaitre les caractéristiques d'un numpy array
array_with_matrice.shape#dimension de l'array 

(3, 3)

In [61]:
#Connaitre le type de l'objet
type(array_with_matrice)#type de l'objet

numpy.ndarray

In [62]:
#Connaitre le type des él
array1.dtype#type des objet

dtype('int32')

In [63]:
array7 = np.array(['1', '2', '3'])
array7.dtype

dtype('<U1')

In [33]:
#Lorsqu'on veut créer un intervalle avec un nombre précis de nombres à l'intérieur, il est plus facile d'utiliser la fonction linspace.
x = np.linspace(0., 10., 50) #remplire un matrice de 50 elements avec des floates between 0 et 10
x

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [35]:
print("le dimension de tab = ", x.ndim)
print("le Forma de tab = ", x.shape)
print("nembre d'elements' tab = ", x.size)
print("type d'elements' tab = ", x.dtype)

le dimension de tab =  1
le Forma de tab =  (50,)
nembre d'elements' tab =  50
type d'elements' tab =  float64


In [37]:
# Liste des tailles en m
tailles = [1.83, 1.85, 1.64, 1.90, 1.72, 1.89, 1.59, 1.68]
# Liste des poids en Kg
poids = [69, 75, 79, 120, 55, 89, 66, 80]
# family_data
family_data = np.array([tailles, poids])
print(family_data)
print("le dimension de tab = ", family_data.ndim)
print("le Forma de tab = ", family_data.shape)
print("nembre d'elements' tab = ", family_data.size)
print("type d'elements' tab = ", family_data.dtype)

[[  1.83   1.85   1.64   1.9    1.72   1.89   1.59   1.68]
 [ 69.    75.    79.   120.    55.    89.    66.    80.  ]]
le dimension de tab =  2
le Forma de tab =  (2, 8)
nembre d'elements' tab =  16
type d'elements' tab =  float64


In [38]:
# Taille moyenne
taille_moy = np.mean(family_data[0])
print("Taille moyenne ", taille_moy)
# Taille médiane
taille_med = np.median(family_data[0])
print("Taille médiane ", taille_med)
# Ecart-type de la taille
taille_std = np.std(family_data[0])
print("Ecart-type de la taille ", taille_std)
# Poids moyen
poids_moy = np.mean(family_data[1])
print("Poids moyen ", poids_moy)
# Poids median
poids_med = np.median(family_data[1])
print("Poids median ", poids_med)
# Ecart-type du poids
poids_std = np.std(family_data[1])
print("Ecart-type du poids ", poids_std)

Taille moyenne  1.7625000000000002
Taille médiane  1.775
Ecart-type de la taille  0.1122218784373172
Poids moyen  79.125
Poids median  77.0
Ecart-type du poids  18.17579090438708


Imaginez que vous meniez une enquête à l'échelle de votre ville où vous interrogez 100000 personnes sur leur taille et leur poids. Vous vous retrouverez avec un tableau numpy en 2D comme celui de family_data mais cette fois-ci avec 100000 colonnes et 2 lignes (taille et poids). Qu'en serait-il à l'échelle d'un département ? d'une région ? d'un pays ou d'un continent ? Vous pouvez vous retrouver très facilement avec des millions voir des milliards chiffres. Que faire ?

A présent, afin de voir vraiment la puissance et la rapidité de calcul de Numpy, nous allons générer de manière aléatoire des données de poids et de taille pour 10000 personnes puis effectuer des calculs statistiques sur cet échantillon.

In [44]:
# Générer des données
tailles_city = np.round(np.random.normal(1.76, 0.11, 100000), 2)
poids_city = np.round(np.random.normal(79.13, 18.18, 100000), 2)

print(tailles_city)
print(poids_city)

[1.71 1.66 1.83 ... 1.76 1.84 1.79]
[103.9   99.51  46.96 ...  56.67  87.65 115.24]


In [54]:
# Générer des données
tailles_city = np.random.randint(1, 20, (100000, 1))
poids_city = np.random.randint(1, 20, (100000, 1))

print(tailles_city)
print(poids_city)

[[14]
 [13]
 [ 6]
 ...
 [10]
 [12]
 [11]]
[[ 8]
 [ 2]
 [15]
 ...
 [12]
 [ 4]
 [19]]


In [61]:
# Générer des données
tailles_city = np.random.normal(loc=1, scale=100, size=(2, 3))
poids_city = np.random.normal(loc=100, scale=2, size=(2, 3))

print(tailles_city)
print(poids_city)

[[ 113.23798091 -104.08506989  107.04258505]
 [ -12.56542281   66.25549073   31.7400199 ]]
[[100.12204322  96.31338523 102.37871596]
 [103.72819812 102.24078245 101.3806129 ]]


In [62]:
# Mettre les tailles sur la première ligne et les poids en deuxième ligne
    # np.array(tailles_city, poids_city)
    
# Coller par colonnes 
    #(tailles_city en première colonne et poids_city en deuxième colonne)
    
data_city = np.column_stack((tailles_city, poids_city))
data_city

array([[ 113.23798091, -104.08506989,  107.04258505,  100.12204322,
          96.31338523,  102.37871596],
       [ -12.56542281,   66.25549073,   31.7400199 ,  103.72819812,
         102.24078245,  101.3806129 ]])

In [63]:
tab4 = np.ones((8, 8), dtype = int)
tab4[1:-1, 1:-1] = 0
print(tab4)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


In [3]:
#importer fichier text numpy
data_array = np.loadtxt("meteo.txt")
data_array

array([[16.3,  0. , 23. , 36. ],
       [15.1,  0.2, 26. , 28. ],
       [15.6,  0. , 22. , 50. ],
       [14.9,  0.1, 32. , 59. ],
       [14.3,  0. , 58. , 58. ],
       [11.5, 15. , 70. , 60. ],
       [10.8,  8.7, 85. , 62. ]])

In [4]:
type(data_array)

numpy.ndarray